name: AutoClockIn
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: python index.py $EMAIL $PASSWD $KEY
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          KEY: ${{ secrets.KEY }}
      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@test.com"
          git add .
          git commit -m "update"
          git push -f
