name: Suying666-auto-clock-in
于:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run script
        run: python index.py $EMAIL $PASSWD $KEY
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          KEY: ${{ secrets.KEY }}
      - name: Commit and push
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "auto update"
          git push
        env:
          EMAIL: ${{ secrets.EMAIL }}
